### ISSUE TITLE
Trouble with build.xml

### ISSUE THREAD

**Issue by jeffThompson** [fjenett/combinatorics#1]
Great library!  I had some trouble building the library, until I commented out the Google Closure Compiler... now everything seems fine.  Not sure if I lost something in that process, but the examples all work without it.

**Comment by fjenett** [comment]
The build file is pretty much just for myself .. you should not need to build anything btw. the downloads contain a build: https://github.com/fjenett/combinatorics/tags

**Comment by jeffThompson** [comment]
Hmm - I might just be confused (completely likely).  I see the .java files but not a single .jar in the typical Processing library structure.  Perhaps just a quick note in the Readme about install would be helpful.  In any case, a super library!

**Comment by fjenett** [comment]
Uh yes you are right .. i mixed things up. The current official release is under Downloads now .. The upcoming Processing has a library manager that handles all the downloading / updating inside Processing. For now you would use the zip under Downloads, that should contain a build. Will add a note to the readme.
