### ISSUE TITLE
ArrayIndexOutOfBoundsException for CombinationSets examples

### ISSUE THREAD

**Issue by jeffThompson** [fjenett/combinatorics#2]
One more issue I noticed (in an otherwise awesome set of tools): the first two CombinationsSets examples don't work (the third does).  They throw an ArrayIndexOutOfBoundsException when creating the new CombinationSets object.

**Comment by fjenett** [comment]
Fixed in nightly ... will be in the next release.
https://github.com/fjenett/combinatorics/zipball/nightly

**Comment by fjenett** [comment]
And thanks for reporting! :)
